name: skip14_trigger

on:
  workflow_dispatch:
  repository_dispatch:
    types: [skip14_trigger]

jobs:
  skip14:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync

      - name: Apply Changes
        if: github.ref == 'refs/heads/main'
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: |
          doppler run -p 20206205tech -c prod -- uv run python temp14.py

      - name: step_clean_document_pending
        if: always()
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: |
          doppler run -p 20206205tech -c prod -- uv run python step_clean_document_pending.py
